added relationship to existing standards to readme
lucimobility/wheelchair-digital-interface pull request #7
Opened 2023-06-06 21:15 UTC by jeredhdean

Added a little more background on where the WDI fits in existing standards and industry history. Is it clear enough?

2023-06-06 23:06 UTC, doudulac reviewed
I would call out the one way, or input only, nature of (all/most) TRACE implementations.

2023-06-07 00:10 UTC, doudulac approved these changes

2023-06-07 17:34 UTC, aaamorgan requested changes
Small grammar change and I'll approve.

2023-06-07 17:34 UTC, aaamorgan commented on README.md
> +WDI is intended to fill a gap in current power wheelchair standards. RESNA WC-2 and ISO 7176 do not define or provide guidance on power wheelchair interfaces for third party input devices. And previo
combine sentences -> "...for third party input devices, and previous attempts..."

2023-06-07 18:45 UTC, aaamorgan approved these changes

2023-06-07 20:12 UTC, merged